language: ruby
sudo: false

## speeding up
#env:
#  - TEST_SUITE=units
#  - TEST_SUITE=integration
#
#script: "bundle exec rake test:$TEST_SUITE"

#bundler_args: --without test
#bundler_args: --without production
bundler_args: --without development

before_install: rm -f Gemfile.lock

rvm:
  - 2.4.1
  - 2.3.1
#  - 2.2.7  # working for Rails 5
#  - 2.2.0  # failing for Rails 5

gemfile:
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_4.gemfile

notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - gemfile: gemfiles/rails_5.0.gemfile
      rvm: 2.2.0
    - gemfile: gemfiles/rails_5.1.gemfile
      rvm: 2.2.0
