language: ruby
#bundler_args: --without production
#before_install: rm -f Gemfile.lock

rvm:
  - 2.4.1
  - 2.3.1
  - 2.2.0

gemfile:
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_4.gemfile

notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - gemfile: gemfiles/rails_4.gemfile
      rvm: 2.4.1
    - gemfile: gemfiles/rails_5.0.gemfile
      rvm: 2.2.0
